### PR TITLE
update @kentcdodds/workshop-app

### PR DESCRIPTION
**Pull request by kettanaito**
Updates the App dependency so the new workshops created already have it (hasn't been an update to this template since November).

### CODE REVIEW

**Comment by kettanaito** [comment]
@kentcdodds, running the `npm run setup` script on this template repo using the latest App version throws this error on the "Custom Setup" step:

```sh
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './apps.server' is not defined by "exports" in /Users/kettanaito/Projects/epicweb/workshops/workshop-template/node_modules/@kentcdodds/workshop-app/package.json imported from /Users/kettanaito/Projects/epicweb/workshops/workshop-template/scripts/setup-custom.js
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:366:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:713:9)
    at packageResolve (node:internal/modules/esm/resolve:899:14)
    at moduleResolve (node:internal/modules/esm/resolve:973:20)
    at defaultResolve (node:internal/modules/esm/resolve:1193:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:403:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:372:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:249:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```

I think we talked about this before. Do you remember what was the fix for this? 

This seems to be the problem with the exports of `@kentcdodds/workshop-app`. I will look into this. 

_Update:_ It looks like the `apps.server` part is not exported in `@kentcdodds/workshop-utils`: 

https://github.com/epicweb-dev/kcdshop/blob/de8e6a41db61a2c7bd872dec5dc801bc8dad3efb/packages/workshop-utils/package.json#L10

**Comment by kettanaito** [comment]
@kentcdodds, I've added `@kentcdodds/workshop-utils` as a dependency to this template so the `setup-custom.js` works. Let me know if this is the direction you see this going but it fixes the template.

**Comment by kettanaito** [comment]
The workshop app itself is broken for me on runtime:

Screenshot 2024-02-28 at 12 22 13

I'm suspecting maybe this is a very old repo and shouldn't be used anymore? If not, we need to make it display the exercises correctly. 

The setups I ran were from the README:

- `npm install`
- `npm run setup`
- `npm run dev`

**Review by kentcdodds — APPROVED** [review]
This is good 👍

**Pull request merged**
